name: prime_lawyer_mobile_app
description: Prime Lawyer MVP mobile application.
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  device_info_plus: ^11.1.0
  flutter_secure_storage: ^9.2.2
  file_picker: ^8.1.2
  image_picker: ^1.1.2
  pdf: ^3.11.1
  flutter_pdfview: ^1.4.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
